name: CI

on:
  pull_request:
  push:

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
      - name: Formatting and linting checks
        run: biome ci .
      - name: Spelling checks
        uses: streetsidesoftware/cspell-action@v6
